CREATE TABLE PROPERTY_MASTER
(
 PROPERTY_ID NUMBER(10) PRIMARY KEY,
 PROPERTY_NAME VARCHAR(50),
 TYPE VARCHAR(5) CHECK(TYPE IN('PLOT','VILLA','FLAT')),
 LOCATION VARCHAR(20),
 PRICE NUMBER(12,2) ,
 STATUS VARCHAR(15) CHECK(UPPER(STATUS) IN ('AVAILABLE','BOOKED','SOLD'))
 )