 CREATE TABLE CUSTOMER_MASTER
 (
 CUSTOMER_ID NUMBER(10) PRIMARY KEY,
 CUSTOMER_NAME VARCHAR(50),
 CONTACT_NO NUMBER(12),
 EMAIL VARCHAR(50) CHECK(UPPER(EMAIL) LIKE '%@GMAIL.COM'),
 ADDRESS VARCHAR(100)
 )