CREATE TABLE BOOKING_MASTER
       (BOOKING_ID NUMBER(10) PRIMARY KEY,
 PROPERTY_ID NUMBER(10),
 CUSTOMER_ID NUMBER(10),
 AGENT_ID NUMBER(10),
 BOOKING_DATE DATE,
 BOOKING_AMOUNT NUMBER(12,2),
 STATUS VARCHAR(10) CHECK(UPPER(STATUS) IN ('BOOKED','CANCELLED')),
 CONSTRAINT PID_FK FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTY_MASTER(PROPERTY_ID),
 CONSTRAINT CID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID),
 CONSTRAINT AID_FK FOREIGN KEY(AGENT_ID) REFERENCES AGENT_MASTER(AGENT_ID))