CREATE TABLE MAINTENANCE_MASTER
 (MAINTENANCE_ID NUMBER(10) PRIMARY KEY,
 PROPERTY_ID NUMBER(10),
 ISSUE_DESCRIPTION VARCHAR(200),
 MAINT_STATUS VARCHAR(10) CHECK(UPPER(MAINT_STATUS) IN ('OPEN','CLOSED')),
 UPDATED_ON DATE,
 CONSTRAINT PID_FK2 FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTY_MASTER(PROPERTY_ID))