CREATE TABLE OWNERSHIP_MASTER
 (OWNER_ID NUMBER(10) PRIMARY KEY,
  PROPERTY_ID NUMBER(10) ,
 CUSTOMER_ID NUMBER(10),
 OWNERSHIP_DATE DATE,
 CONSTRAINT PID_FK3 FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTY_MASTER(PROPERTY_ID),
 CONSTRAINT CID_FK2 FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_MASTER(CUSTOMER_ID)
 )