CREATE OR REPLACE PROCEDURE ADD_PROPERTY
 (VPROPERTY_ID IN PROPERTY_MASTER.PROPERTY_ID%TYPE,
  VPROPERTY_NAME IN PROPERTY_MASTER.PROPERTY_NAME%TYPE,
  VTYPE IN PROPERTY_MASTER.TYPE%TYPE,
  VLOCATION IN PROPERTY_MASTER.LOCATION%TYPE,
  VPRICE IN PROPERTY_MASTER.PRICE%TYPE,
  VSTATUS IN PROPERTY_MASTER.STATUS%TYPE,
  VOUT OUT VARCHAR2)
AS
BEGIN
INSERT INTO PROPERTY_MASTER VALUES (VPROPERTY_ID,VPROPERTY_NAME,VTYPE,VLOCATION,VPRICE,VSTATUS)
VOUT:='RECORD HAS BEE INSERTED';
END;

// VAR B1 VARCHAR2(200);
// EXEC ADD_PROPERTY(0000,'XXX','VILLA','PUNW',909009,'SOLD');
// PRINT B1;
