CREATE OR REPLACE PROCEDURE UPDATE_PROPERTY_PRICE(VPROPERTY_ID IN PROPERTY_MASTER.PROPERTY_ID%TYPE
 VPRICE IN PROPERTY_MASTER.PRICE%TYPE ,VOUT OUT VARCHAR2)
 AS
 BEGIN
 UPDATE PROPERTY_MASTER
 SET PRICE=VPRICE
 WHERE PROPERTY_ID=VPROPERTY_ID;
 VOUT:='PRICE UPDATED AT'||VPROPERTY_ID;
 END;
// VAR B1 VARCHAR2(200);
//EXEC UPDATE_PROPERTY_PRICE(0000,999988,:B1);
//PRINT B1;

