CREATE OR REPLACE PROCEDURE REGISTER_CUSTOMER (
VCUSTID IN CUSTOMER_MASTER.CUSTOMER_ID%TYPE,
VCNAME IN CUSTOMER_MASTER.CUSTOMER_NAME%TYPE,
VCONTACT IN CUSTOMER_MASTER.CONTACT_NO%TYPE,
VEMAIL IN CUSTOMER_MASTER.EMAIL%TYPE,
VADDRESS IN CUSTOMER_MASTER.ADDRESS%TYPE,
VOUT OUT VARCHAR2)
AS
BEGIN
INSERT INTO CUSTOMER_MASTER VALUES(VCUSTID,VCNAME ,VCONTACT,VEMAIL,VADDRESS );
VOUT:='REGISTERD SUCCESSFULLY';
END;

//VAR B1 VARCHAR2(200);
//EXEC REGISTER_CUSTOMER(000,'XYZ',1234567898,'AS@GMAIL.COM,'GGFFHH',:B1);VAR B1 VARCHAR2(200);
