CREATE OR REPLACE PROCEDURE BOOK_PROPERTY
 (
     VBOOKING_ID     IN BOOKING_MASTER.BOOKING_ID%TYPE,
     VPROPERTY_ID    IN BOOKING_MASTER.PROPERTY_ID%TYPE,
     VCUSTOMER_ID    IN BOOKING_MASTER.CUSTOMER_ID%TYPE,
     VAGENT_ID       IN BOOKING_MASTER.AGENT_ID%TYPE,
     VBOOKING_DATE   IN BOOKING_MASTER.BOOKING_DATE%TYPE,
     VAMOUNT         IN BOOKING_MASTER.BOOKING_AMOUNT%TYPE,
     VOUT            OUT VARCHAR2
 )
 AS
 BEGIN
     INSERT INTO BOOKING_MASTER
     VALUES (VBOOKING_ID, VPROPERTY_ID, VCUSTOMER_ID, VAGENT_ID, SYSDATE, VAMOUNT, 'BOOKED');
     UPDATE PROPERTY_MASTER
     SET STATUS = 'BOOKED'
     WHERE PROPERTY_ID = VPROPERTY_ID;
     VOUT := 'PROPERTY BOOKED SUCCESSFULLY';
 END;
 /