CREATE OR REPLACE PROCEDURE CANCEL_BOOKING
(
    VBOOKING_ID  IN BOOKING_MASTER.BOOKING_ID%TYPE,
    VOUT         OUT VARCHAR2
)
AS
    VPROP_ID PROPERTY_MASTER.PROPERTY_ID%TYPE;
BEGIN
SELECT PROPERTY_ID INTO VPROP_ID
FROM BOOKING_MASTER
WHERE BOOKING_ID =VbOOKING_ID;
UPDATE BOOKING_MASTER
SET STATUS='CANCELLED'
WHERE BOOKING_ID=VBOOKING_ID;
UPDATE PROPERTY_MASTER
SET STATUS='AVAILABLE'
WHERE PROPERTY_ID=VPROP_ID;
VOUT:='BOOKING CANCELLED';
END;
/