 CREATE OR REPLACE PROCEDURE RECORD_PAYMENT
 (
     VPAY_ID     IN PAYMENT_MASTER.PAYMENT_ID%TYPE,
     VBOOKING_ID IN PAYMENT_MASTER.BOOKING_ID%TYPE,
     VPAY_DATE   IN PAYMENT_MASTER.PAYMENT_DATE%TYPE,
     VAMOUNT     IN PAYMENT_MASTER.PAYMENT_AMOUNT%TYPE,
     VMODE       IN PAYMENT_MASTER.PAYMENT_MODE%TYPE,
     VOUT        OUT VARCHAR2
 )
 AS
     VSTATUS BOOKING_MASTER.STATUS%TYPE;
 BEGIN
     SELECT STATUS INTO VSTATUS
     FROM BOOKING_MASTER
     WHERE BOOKING_ID = VBOOKING_ID;
     IF VSTATUS != 'BOOKED' THEN
         VOUT := 'PAYMENT NOT ALLOWED BOOKING IS NOT ACTIVE';
         RETURN;
     END IF;
     INSERT INTO PAYMENT_MASTER
     VALUES (VPAY_ID, VBOOKING_ID, SYSDATE, VAMOUNT, VMODE);
     VOUT := 'PAYMENT RECORDED SUCCESSFULLY';
 END;
/