 CREATE OR REPLACE PROCEDURE ADD_MAINTENANCE_REQUEST
 (
     VMAIN_ID        IN MAINTENANCE_MASTER.MAINTENANCE_ID%TYPE,
     VPROPERTY_ID   IN MAINTENANCE_MASTER.PROPERTY_ID%TYPE,
     VISSUE         IN MAINTENANCE_MASTER.ISSUE_DESCRIPTION%TYPE,
     VM_STATUS      IN MAINTENANCE_MASTER.MAINT_STATUS%TYPE,
     VUPDATED_ON    IN MAINTENANCE_MASTER.UPDATED_ON%TYPE,
     VOUT           OUT VARCHAR2
 )
 AS
 BEGIN
     INSERT INTO MAINTENANCE_MASTER
     VALUES (VMAIN_ID, VPROPERTY_ID, VISSUE, 'OPEN', SYSDATE);
     VOUT := 'MAINTENANCE REQUEST CREATED';
 END;
 /