CREATE OR REPLACE PROCEDURE CLOSE_MAINTENANCE
  (
      VMAIN_ID IN MAINTENANCE_MASTER.MAINTENANCE_ID%TYPE,
      VOUT    OUT VARCHAR2
  )
  AS
  BEGIN
      UPDATE MAINTENANCE_MASTER
      SET MAINT_STATUS = 'CLOSED',
          UPDATED_ON = SYSDATE
      WHERE MAINTENANCE_ID = VMAIN_ID;
      VOUT := 'MAINTENANCE REQUEST CLOSED';
END;