CREATE OR REPLACE PROCEDURE TRANSFER_OWNERSHIP(
  P_OWNER_ID    IN OWNERSHIP_MASTER.OWNER_ID%TYPE,
  P_PROPERTY_ID IN OWNERSHIP_MASTER.PROPERTY_ID%TYPE,
  P_CUSTOMER_ID IN OWNERSHIP_MASTER.CUSTOMER_ID%TYPE
) AS
BEGIN
  INSERT INTO OWNERSHIP_MASTER(OWNER_ID, PROPERTY_ID, CUSTOMER_ID, OWNERSHIP_DATE)
  VALUES (P_OWNER_ID, P_PROPERTY_ID, P_CUSTOMER_ID, SYSDATE);

  UPDATE PROPERTY_MASTER
  SET STATUS = 'SOLD'
  WHERE PROPERTY_ID = P_PROPERTY_ID;
END;
/