CREATE OR REPLACE PROCEDURE GET_PROPERTY_DETAILS
(
    VPROPERTY_ID IN PROPERTY_MASTER.PROPERTY_ID%TYPE,
    VOUT         OUT VARCHAR2
)
AS
    VDETAILS VARCHAR2(3000);
BEGIN
    SELECT 'PROPERTY: ' || PROPERTY_NAME ||
           ', LOCATION: ' || LOCATION ||
           ', PRICE: ' || PRICE ||
           ', STATUS: ' || STATUS
    INTO VDETAILS
    FROM PROPERTY_MASTER
    WHERE PROPERTY_ID = VPROPERTY_ID;

    VOUT := VDETAILS;
END;

