CREATE OR REPLACE TRIGGER TRG_BOOKING_VALIDATE
 BEFORE INSERT ON BOOKING_MASTER
 FOR EACH ROW
 DECLARE
     v_status BOOKING_MASTER.STATUS%TYPE;
 BEGIN
     SELECT STATUS INTO v_status
     FROM PROPERTY_MASTER
     WHERE PROPERTY_ID = :NEW.PROPERTY_ID;
     IF v_status != 'AVAILABLE' THEN
         RAISE_APPLICATION_ERROR(-20001,'Property is already BOOKED/SOLD.');
     END IF;
 END;
