CREATE OR REPLACE TRIGGER TRG_PAYMENT_VALIDATE
BEFORE INSERT ON PAYMENT_MASTER
FOR EACH ROW
DECLARE
    V_TOTAL NUMBER;
    V_BOOKING_AMOUNT NUMBER;
BEGIN
    SELECT NVL(SUM(PAYMENT_AMOUNT),0)
    INTO V_TOTAL
    FROM PAYMENT_MASTER
    WHERE BOOKING_ID = :NEW.BOOKING_ID;

    SELECT BOOKING_AMOUNT
    INTO V_BOOKING_AMOUNT
    FROM BOOKING_MASTER
    WHERE BOOKING_ID = :NEW.BOOKING_ID;

    IF V_TOTAL + :NEW.PAYMENT_AMOUNT > V_BOOKING_AMOUNT THEN
        RAISE_APPLICATION_ERROR(-20012, 'PAYMENT EXCEEDS BOOKING AMOUNT');
    END IF;
END;
/
