CREATE OR REPLACE TRIGGER TRG_PROPERTY_PRICE_HISTORY
 AFTER UPDATE OF PRICE ON PROPERTY_MASTER
 FOR EACH ROW
 DECLARE
     NEW_LOG_ID NUMBER;
 BEGIN
     SELECT NVL(MAX(LOG_ID),0) + 1 INTO NEW_LOG_ID FROM AUDIT_LOG;
     INSERT INTO AUDIT_LOG(LOG_ID, TABLE_NAME, OPERATION_TYPE, DESCRIPTION, LOG_DATE)
     VALUES (
         NEW_LOG_ID,
         'PROPERTY_MASTER',
         'PRICE_UPDATE',
         'OLD PRICE=' || :OLD.PRICE || ' NEW PRICE=' || :NEW.PRICE,
         SYSDATE
     );
 END;
 /

