CREATE OR REPLACE TRIGGER TRG_CUSTOMER_CONTACT_DUPLICATE
BEFORE INSERT ON CUSTOMER_MASTER
FOR EACH ROW
DECLARE
    V_CNT NUMBER;
BEGINS
    SELECT COUNT(*) INTO V_CNT
    FROM CUSTOMER_MASTER
    WHERE CONTACT_NO = :NEW.CONTACT_NO;

    IF V_CNT > 0 THEN
        RAISE_APPLICATION_ERROR(-20013, 'CONTACT NUMBER ALREADY EXISTS');
    END IF;
END;