CREATE OR REPLACE TRIGGER TRG_AUDIT_BOOKING
AFTER INSERT OR UPDATE OR DELETE ON BOOKING_MASTER
FOR EACH ROW
DECLARE
    NEW_LOG_ID NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_ID),0) + 1 INTO NEW_LOG_ID FROM AUDIT_LOG;

    IF INSERTING THEN
        INSERT INTO AUDIT_LOG VALUES (NEW_LOG_ID, 'BOOKING_MASTER', 'INSERT', 'BOOKING CREATED', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO AUDIT_LOG VALUES (NEW_LOG_ID, 'BOOKING_MASTER', 'UPDATE', 'BOOKING UPDATED', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO AUDIT_LOG VALUES (NEW_LOG_ID, 'BOOKING_MASTER', 'DELETE', 'BOOKING DELETED', SYSDATE);
    END IF;
END;
/
