CREATE OR REPLACE TRIGGER TRG_AUDIT_PAYMENT
AFTER INSERT OR UPDATE ON PAYMENT_MASTER
FOR EACH ROW
DECLARE
    NEW_LOG_ID NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_ID),0) + 1 INTO NEW_LOG_ID FROM AUDIT_LOG;

    IF INSERTING THEN
        INSERT INTO AUDIT_LOG VALUES (NEW_LOG_ID, 'PAYMENT_MASTER', 'INSERT', 'PAYMENT ADDED', SYSDATE);
    ELSE
        INSERT INTO AUDIT_LOG VALUES (NEW_LOG_ID, 'PAYMENT_MASTER', 'UPDATE', 'PAYMENT UPDATED', SYSDATE);
    END IF;
END;
/