CREATE OR REPLACE TRIGGER TRG_BLOCK_UPDATE_AFTER_SOLD
BEFORE UPDATE ON PROPERTY_MASTER
FOR EACH ROW
BEGIN
    IF :OLD.STATUS = 'SOLD' THEN
        RAISE_APPLICATION_ERROR(-20014, 'CANNOT UPDATE SOLD PROPERTY');
    END IF;
END;
/