CREATE OR REPLACE TRIGGER TRG_BOOKING_DATE_LOCK
BEFORE INSERT ON BOOKING_MASTER
FOR EACH ROW
BEGIN
    IF TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') = 'SUN' THEN
        RAISE_APPLICATION_ERROR(-20015, 'BOOKINGS NOT ALLOWED ON SUNDAY');
    END IF;
END;
/
