CREATE OR REPLACE TRIGGER TRG_PROPERTY_STATUS_CONTROL
AFTER INSERT ON OWNERSHIP_MASTER
FOR EACH ROW
BEGIN
    UPDATE PROPERTY_MASTER
    SET STATUS = 'SOLD'
    WHERE PROPERTY_ID = :NEW.PROPERTY_ID;
END;
/