 CREATE VIEW VW_BOOKING_DETAILS  AS
   SELECT B.BOOKING_ID,B.PROPERTY_ID,B.CUSTOMER_ID,
   B.AGENT_ID,B.BOOKING_DATE ,B.BOOKING_AMOUNT,
   B.STATUS,A.AGENT_NAME,A.PHONE,A.COMMISION_PERCENT,
   C.CUSTOMER_NAME,C.CONTACT_NO,C.EMAIL,C.ADDRESS
  FROM BOOKING_MASTER B INNER JOIN AGENT_MASTER A
   ON B.AGENT_ID=A.AGENT_ID INNER JOIN CUSTOMER_MASTER C
   ON B.CUSTOMER_ID =C.CUSTOMER_ID