 CREATE VIEW VW_PAYMENT_HISTORY  AS
     SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CONTACT_NO,P.BOOKING_ID ,P.PAYMENT_ID,PAYMENT_DATE,P.PAYMENT_AMOUNT,P.PAYMENT_MODE
     FROM PAYMENT_MASTER P INNER JOIN BOOKING_MASTER B
     ON P.BOOKING_ID=B.BOOKING_ID INNER JOIN CUSTOMER_MASTER C
     ON B.CUSTOMER_ID=C.CUSTOMER_ID
