CREATE VIEW VW_OWNERSHIP_DETAILS AS  
    SELECT P.PROPERTY_ID,P.PROPERTY_NAME,O.OWNER_ID,O.CUSTOMER_ID,
    C.CUSTOMER_NAME AS OWNER,C.CONTACT_NO,C.EMAIL,C.ADDRESS,O.OWNERSHIP_DATE
    FROM PROPERTY_MASTER P INNER JOIN OWNERSHIP_MASTER O
    ON P.PROPERTY_ID=O.PROPERTY_ID INNER JOIN CUSTOMER_MASTER C
    ON O.CUSTOMER_ID=C.CUSTOMER_ID