CREATE VIEW VW_CUSTOMER_PROFILE AS
    SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,B.BOOKING_ID,B.PROPERTY_ID,B.BOOKING_DATE,B.BOOKING_AMOUNT,B.STATUS
    FROM CUSTOMER_MASTER C INNER JOIN BOOKING_MASTER B
    ON C.CUSTOMER_ID=B.CUSTOMER_ID
