 CREATE VIEW VW_PROPERTY_FULL_INFO   AS
 SELECT
     P.PROPERTY_ID,
     P.PROPERTY_NAME,
     P.LOCATION,
     P.PRICE,
     P.TYPE,
     P.STATUS AS PROPERTY_STATUS,
     B.BOOKING_ID,
     B.BOOKING_DATE,
     B.BOOKING_AMOUNT,
     B.STATUS AS BOOKING_STATUS,
     C.CUSTOMER_ID,
     C.CUSTOMER_NAME,
     C.CONTACT_NO AS CUSTOMER_CONTACT,
     C.EMAIL AS CUSTOMER_EMAIL,
     C.ADDRESS AS CUSTOMER_ADDRESS,
     A.AGENT_ID,
     A.AGENT_NAME,
     A.PHONE AS AGENT_PHONE,
     A.COMMISION_PERCENT
 FROM PROPERTY_MASTER P
 INNER JOIN BOOKING_MASTER B
     ON P.PROPERTY_ID = B.PROPERTY_ID
 INNER JOIN CUSTOMER_MASTER C
     ON B.CUSTOMER_ID = C.CUSTOMER_ID
 INNER JOIN AGENT_MASTER A
     ON B.AGENT_ID = A.AGENT_ID;
   